import './globals.css';

import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'My Audio Player',
    description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="ko">
            <body>
                <main className="flex min-h-screen w-full flex-col items-center justify-center gap-2.5">{children}</main>
            </body>
        </html>
    );
}
